# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a61f65271e7d6284c01ecd4a1eaa86b6828e51a642087738422e19d9146f11c0c045c7cfd3e1aa70b23dc5684ad1a0ae7584c5bdb3e5072841e6675bd4664c

test:
  secret_key_base: 3a488484a2289cc0d1dc470fa157d6d5f8008dd6b77a4820c188b961490db71a8a0f50d84c3f6648fcaa0c3276cc4ddc179fb520b70bd1b275ab0656412c2231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
